name: bebidas_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  font_awesome_flutter: ^10.10.0
  

  # Firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.2

  # Utils
  image_picker: ^1.2.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  share_plus: ^10.1.4
  path_provider: ^2.1.5       # <- CORRECTO (no “patch_provider”)
  csv: ^5.0.2                 # <- para exportar CSV
  http: ^1.2.2
  qr_flutter: ^4.1.0

  # Location / Map
  geolocator: ^12.0.0
  location: ^6.0.2
  google_maps_flutter: ^2.7.0
  geocoding: ^2.2.0
  flutter_map: ^6.1.0
  package_info_plus: ^8.0.0
  latlong2: ^0.9.0
  
  
  # Charts
  fl_chart: ^0.66.2

  #Iconografia
  phosphor_flutter: ^2.0.1

  # Localizations
  flutter_localizations:
    sdk: flutter

  # Notificaciones
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^17.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/banners/